- name: make /local_home
  file: path=/local_home owner=root group=root state=directory
  sudo: true 

- name: copy the {{ ansible_ssh_user }} home
  shell: cp -ar /home/{{ ansible_ssh_user }} /local_home
  ignore_errors: true
  sudo: true
  register: home_copied


- name: edit passwd file
  lineinfile:
  args:
    dest: /etc/passwd
    regexp: "{{ ansible_ssh_user }}:x:1001:1001::/home/{{ ansible_ssh_user }}:.*"
    line: "{{ ansible_ssh_user }}:x:1001:1001::/local_home/{{ ansible_ssh_user }}:/bin/bash"
    backrefs: yes
  sudo: true
  register: edit1


- name: edit passwd file
  lineinfile:
  args:
    dest: /etc/passwd
    regexp: "{{ ansible_ssh_user }}:x:500:500::/home/{{ ansible_ssh_user }}:.*"
    line: "{{ ansible_ssh_user }}:x:500:500::/local_home/{{ ansible_ssh_user }}:/bin/bash"
    backrefs: yes
  sudo: true
  register: edit2



- name: edit passwd file
  lineinfile:
  args:
    dest: /etc/passwd
    regexp: "{{ ansible_ssh_user }}:x:1000:1000::/home/{{ ansible_ssh_user }}:.*"
    line: "{{ ansible_ssh_user }}:x:1000:1000::/local_home/{{ ansible_ssh_user }}:/bin/bash"
    backrefs: yes
  sudo: true
  register: edit3

# ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
- name: edit passwd file for ubuntu 14
  lineinfile:
  args:
    dest: /etc/passwd
    regexp: "{{ ansible_ssh_user }}:x:1000:1000:Ubuntu:/home/{{ ansible_ssh_user }}:.*"
    line: "{{ ansible_ssh_user }}:x:1000:1000:/Ubuntu:local_home/{{ ansible_ssh_user }}:/bin/bash"
    backrefs: yes
  sudo: true
  register: edit4

