---
- name: "Installing MySQL Debian"
  apt: name="{{ item }}" update_cache=yes cache_valid_time=3600 state=present
  with_items: client_packages
  sudo: true
  when: ansible_os_family == "Debian"

- name: Installing MySQL RedHat
  yum: name="{{ item }}" state=present
  with_items: client_packages
  sudo: true
  when: ansible_os_family == "RedHat"
