---
- name: stat
  stat: path={{ dest }}
  register: stat_r


- name: debug1
  debug: var=stat_r

- name: mv
  command: mv "{{ dest }}" "{{ dest }}_old"
  when: stat_r.stat.exists and stat_r.stat.isdir
  sudo: true

- name: stat 
  stat: path={{ dest }}
  register: stat_r

- name: debug2
  debug: var=stat_r

- name: link
  file: src="{{ src }}" dest="{{ dest }}" state=link
  when: not stat_r.stat.exists
  sudo: true
