--- 
- name: "Create exports if necessary"
  file: dest={{ item.src }} state=directory mode=755 owner=root group=root
  sudo: true
  with_items: exportList

- name: "Starting rpcbind"
  service: "name=rpcbind state=started enabled=true"
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "Start the Server"
  service: "name=nfs state=started enabled=true"
  sudo: true
  when: ansible_os_family == "RedHat"

- name: "Start the Server"
  service: "name=nfs-kernel-server state=started enabled=true"
  sudo: true
  when: ansible_os_family == "Debian"
