---
- name: grab cacert
  shell: cat {{ ldapCARootDest }} 
  register: ldapCaCertContents

- name: dump vars
  template: src=ldapConfig.j2 dest=/tmp/ldapConfig.out

- name: fetch vars
  fetch: src=/tmp/ldapConfig.out dest=/tmp/ldapConfig.out flat=yes

